# Generated by Django 3.2.16 on 2024-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='adress title of event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='city of event'),
        ),
    ]
