# Generated by Django 3.2.16 on 2024-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240413_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, choices=[('no_experience', 'Нет опыта'), ('from_one_year', 'От 1 года'), ('from_3_years', 'От 3 лет'), ('from_5_years', 'От 5 лет'), ('other', 'Другое')], max_length=128),
        ),
    ]
